version: '3.8'

services:
  # PDF to HTML converter service using pdf2htmlEX
  pdf2htmlex:
    image: bwits/pdf2htmlex:latest
    container_name: pdf2htmlex-service
    volumes:
      - ./uploads:/pdf
    networks:
      - pdf-network

  # Node.js backend service
  backend:
    build: .
    container_name: pdf-transformer-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3001}
    volumes:
      - ./uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - pdf2htmlex
    networks:
      - pdf-network

networks:
  pdf-network:
    driver: bridge